### ISSUE TITLE
unable to access csv files from s3

### ISSUE THREAD

**Issue by dlevine01** [austensen/oca#15]
When trying to download any of the csv files (e.g. https://oca-2-dev.s3.amazonaws.com/public/oca_index.csv) I get this error response:

```xml
<Error>
  <Code>InvalidArgument</Code>
  <Message>Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4.</Message>
  <ArgumentName>Authorization</ArgumentName>
  <ArgumentValue>null</ArgumentValue>
  <RequestId>AFVC85FVTCCD1BQM</RequestId>
  <HostId>t08yVTuuMb9nQdn0ar3Jfsxr8Kez6Pd/EWZJoRJneCW2hdkR5biJ+PAg4hY0qmbILYk2q5CPxiM=</HostId>
</Error>
```

This is also means `nycdb --download oca` does not work

**Comment by austensen** [comment]
Hey @dlevine01 Thanks for letting us know - we've fixed the issue

**Comment by dlevine01** [comment]
thanks for the quick fix @austensen !

**Comment by dlevine01** [comment]
I'm getting the same error response again

at https://oca-2-dev.s3.amazonaws.com/public/oca_index.csv I get:

```xml
<Error>
<Code>InvalidArgument</Code>
<Message>Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4.</Message>
<ArgumentName>Authorization</ArgumentName>
<ArgumentValue>null</ArgumentValue>
<RequestId>36M41M7K7T0XXXHT</RequestId>
<HostId>kX3/1IyXGFiRs/sOBGWSVi1yGkfIhUFWFxovJhFl8821O9Ofuu3MP2ZQXlo65Jj5w9mgqZdurIM=</HostId>
</Error>
```

**Comment by austensen** [comment]
Hey @dlevine01 thanks again for flagging the problem - sorry this keeps happening, some how in updates it sometimes resets the encryption settings. It should be fixed now. 

And just a note to myself/others in the future - to fix this the encryption settings need to be edited and overwritten for all the public files on S3:
![image](https://github.com/user-attachments/assets/9cf81910-b1aa-4f0d-9e8d-6c317eb06a3f)
![image](https://github.com/user-attachments/assets/69af8cb7-e03d-4aec-973d-5a486cd091c7)

**Comment by dlevine01** [comment]
Thanks for the quick fix @austensen !

**Comment by dlevine01** [comment]
Hello! 

Just flagging that I'm seeing this same error again.

oca_index.csv returns:

```
<Error>
<Code>InvalidArgument</Code>
<Message>Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4.</Message>
<ArgumentName>Authorization</ArgumentName>
<RequestId>M1AKK601TVCV5Z0R</RequestId>
<HostId>rgnKLR3fGpiEYM7gS6RAMzRL18gfYUt54ikCqBUDdz15JCZxuzBpRHlobhGE+GqYQ6AInJngZ+o=</HostId>
</Error>
```
